[project]
name = "rnwolf-newsletter-backend-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "dnspython>=2.7.0",
    "jmapc>=0.2.23",
    "requests>=2.32.4",
    "rich>=14.0.0",
]
